version: '3.1'
services:
  dev_mariadb:
    image: mariadb:10.4.21
    restart: always
    container_name: dev_mariadb
    ports:
      - 13300:3306
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=testdb
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=1234
      - TZ=UTC
    volumes:
      - ~/docker/volumes/new_admin/local_db:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --default-time-zone=Asia/Seoul